config/routes.rb
Tille::Application.routes.draw do

  root :to 			     => 'landing#index'

  get  'dashboard'   => 'counter#index'
  get  'user_root'   => 'counter#index'
  post 'record'      => 'counter#record_time'
  post 'stop-record' => 'counter#stop_recording'
  post 'remove-item' => 'counter#remove_item'
  post 'add_item'    => 'counter#add_item'

  namespace :free_tracker do
    resources :tasks
  end

  devise_for :users
end

app/models/commit.rb
class Commit < ActiveRecord::Base
  attr_accessible :begin_time, :end_time, :spent_time, :item_id

  validates :begin_time, :presence => true
  validates :end_time, 	 :presence => true
  validates :spent_time, :presence => true

  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :estimated_time, :name, :user_id

  validates  :name,           :presence => true #, :uniqueness => true
  validates  :estimated_time, :presence => true, :numericality => true

  has_many   :commits
  has_one    :recording_item
  belongs_to :user

  # should return an string with format #h/#m/#s (hours, minutes, seconds)
  def self.format_time seconds
    hours   = seconds / 3600
    seconds = seconds%3600
    minutes = seconds / 60
    seconds = seconds % 60

    if minutes+seconds == 0
      hours.to_s + "h"
    elsif seconds == 0
      '%dh:%dm' % [hours, minutes]
    elsif minutes == 0
      '%dh:%ds' % [hours, seconds]
    else
      '%dh %dm %ds' % [hours, minutes, seconds]
    end
  end

  def week_time
    Item.format_time week_seconds
  end

  def week_seconds
    week_begin = DateTime.now.utc.beginning_of_week
    deadline   = DateTime.now.utc.end_of_week
    commits.where("begin_time > ? and end_time < ?", week_begin, deadline).sum(:spent_time)
  end

  # this method return the time commited today in format #h#m#s
  def self.today_time
    format_time today_seconds
  end

  # this method should return the seconds commited today
  def self.today_seconds
    beginning_in = DateTime.now.utc.beginning_of_day
    deadline     = DateTime.now.utc.end_of_day
    Commit.where("begin_time > ? and end_time < ?", beginning_in, deadline).sum(:spent_time)
  end

  # this method return the time commited this week in format #h/#m/#s
  def self.week_time
    format_time week_seconds
  end

  # this method should return the seconds commited this week
  def self.week_seconds
    week_begin = DateTime.now.utc.beginning_of_week
    deadline   = DateTime.now.utc.end_of_week
    Commit.where("begin_time > ? and end_time < ?", week_begin, deadline).sum(:spent_time)
  end

  # this method return the seconds commited by one item (self) this week
  def calculate_week_time
    week_begin = DateTime.now.utc.beginning_of_week
    deadline   = DateTime.now.utc.end_of_week
    self.commits.where("begin_time > ? and end_time < ?", week_begin, deadline).sum(:spent_time)
  end
end

app/models/recording_item.rb
class RecordingItem < ActiveRecord::Base
  attr_accessible :record_beginning_at, :item_id

  belongs_to :item
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :items
  has_many :commits, :through => :items

  # this method return the time commited today by this user in format #h#m#s
  def today_time
    Item.format_time today_seconds
  end

  # this method return the seconds commited today by this user
  def today_seconds
    beginning_in = DateTime.now.utc.beginning_of_day
    deadline     = DateTime.now.utc.end_of_day
    self.commits.where("begin_time > ? and end_time < ?", beginning_in, deadline).sum(:spent_time)
  end

  # this method return the time commited this week by this user in format #h/#m/#s
  def week_time
    Item.format_time week_seconds
  end

  # this method should return the seconds commited this week by this user
  def week_seconds
    week_begin = DateTime.now.utc.beginning_of_week
    deadline   = DateTime.now.utc.end_of_week
    self.commits.where("begin_time > ? and end_time < ?", week_begin, deadline).sum(:spent_time)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/counter_controller.rb
class CounterController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user  = current_user
    @items = @user.items
  end

  def record_time
    params_to = { record_beginning_at: Time.now.utc, item_id: params[:item] }
    @recording_item = RecordingItem.new params_to

    if @recording_item.save
      render text: "OK"
    else
      render text: @recording_item.errors.messages
    end
  end

  def stop_recording
    @item = Item.find params[:item]
    @recording_item = @item.recording_item

    if @recording_item
      @begin_time = @recording_item.record_beginning_at
      @end_time   = Time.now.utc - 1.second

      if @begin_time.beginning_of_day != @end_time.beginning_of_day

        spent_1 = @end_time.beginning_of_day.to_i - @begin_time.to_i
        spent_2 = @end_time.to_i - @end_time.beginning_of_day.to_i

        Commit.create(begin_time: @begin_time,
                      end_time:   @end_time.beginning_of_day,
                      spent_time: spent_1,
                      item_id:    params[:item])

        Commit.create(begin_time: @end_time.beginning_of_day,
                      end_time:   @end_time,
                      spent_time: spent_2,
                      item_id:    params[:item])
      else
        spent = @end_time.to_i - @begin_time.to_i
        Commit.create(begin_time: @begin_time,
                      end_time:   @end_time,
                      spent_time: spent,
                      item_id:    params[:item])
      end

      RecordingItem.find(@recording_item.id).destroy
      render text: "OK"
    else
      render text: "this item is not commiting time in this momment!"
    end
  end

  def remove_item
    item_id = params[:item]

    if Commit.where(item_id: item_id).destroy_all and Item.find(item_id).destroy
      render text: "OK"
    else
      render text: "Object cannot be destroyed!!"
    end
  end

  def add_item
    @item = Item.new params[:item]

    if @item.valid?
      @item.estimated_time = params[:item][:estimated_time].to_i*60*60
    end

    if @item.save
      redirect_to dashboard_path, notice: "Item was succesfully created!!"
    else
      redirect_to dashboard_path, alert: @item.errors.full_messages
    end
  end

end

app/controllers/free_tracker/tasks_controller.rb
class FreeTracker::TasksController < ApplicationController
  before_filter :authenticate_user!

  def index
    @tasks = Task.all
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counter_helper.rb
module CounterHelper
end

app/views/counter/index.html.erb
<div class="row-fluid">
  <div class="container">

    <div class="messages-box">
      <% if flash.now[:alert] %>
        <p class="flash-error">
          <ul>
            <% flash.now[:alert].each do |msg| %>
            <li class="alert alert-danger alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= msg %>
            </li>
            <% end %>
          </ul>
        </p>
      <% end %>

      <% if flash.now[:notice] %>
        <p class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= flash.now[:notice] %>
        </p>
      <% end %>
    </div>

    <div class="row time-info">
      <div class="span12">

        <div class="today-seconds">
          <%= @user.today_seconds %>
        </div>
        <div class="week-seconds">
          <%= @user.week_seconds %>
        </div>

        <h3>
          Today <p id="today-time"><%= @user.today_time %></p>
          <p class="muted" style="display: inline;">and</p>
          Week <p id="week-time"><%= @user.week_time %></p>
        </h3>

      </div>
    </div>

    <ul>
      <% @items.each do |item| %>

      <li id="item-container-<%= item.id %>">
        <div>
          <%= item.name %> &nbsp;/&nbsp;

          <% if item.recording_item %>
            <a class="stop-record" id="stop-record-<%= item.id %>"> Stop Recording </a>
            <a class="record" id="record-<%= item.id %>" style="display: none;"> Record Time </a>
          <% else %>
            <a class="stop-record" id="stop-record-<%= item.id %>" style="display: none;"> Stop Recording </a>
            <a class="record" id="record-<%= item.id %>"> Record Time </a>
          <% end %>

          <a class="muted remove-item" id="remove-item-<%= item.id %>" href="#">
            Remove item <i class="icon-remove"></i>
          </a>
        </div>

        <div class="progress progress-success">
          <% week_progress = (item.calculate_week_time * 100) / item.estimated_time %>
          <div class="bar bar-<%= item.id %>"
               data-commited-time=<%= item.calculate_week_time %>
               data-estimated-time=<%= item.estimated_time %>
               style="width: <%= week_progress %>%;">
          </div>
        </div>

        <div>
          <pre>Item progress: <%= item.week_time %></pre>
        </div><br>
      </li>
      <% end %>
    </ul>

    <div class="btn-group" style="padding-left: 300px; margin-top: -30px">
      <button class="btn">Monday</button>
      <button class="btn">Tuesday</button>
      <button class="btn">Wednesday</button>
      <button class="btn">Thursday</button>
      <button class="btn">Friday</button>
      <button class="btn">Saturday</button>
      <button class="btn">Sunday</button>
    </div>

    <hr>
    <div class="add-item-form">
      <h4 class="muted">Add a new item</h4>
      <%= form_for :item, url: add_item_path do |f| %>
        <p>
          <%= f.text_field :name, placeholder: "Item name" %>
          <%= f.text_field :estimated_time, placeholder: "Time per week (hours)" %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.submit "crear", class: "btn btn-inverse create-item-button" %>
        </p>
      <% end %>

      <a class="muted hide-item" href="#">
        Hide form <i class="icon-off"></i>
      </a>
    </div>

    <a class="muted add-item" href="#">
      Add Item to the List <i class="icon-plus-sign"></i>
    </a>

  </div>
</div>

<script type="text/javascript">
  $(".nav-tabs li").removeClass("active");
  $(".nav-tabs li")[1].className += "active";
</script>

app/views/free_tracker/tasks/index.html.erb
<div class="row-fluid">
  <div class="container">
    <h1>Tasks</h1>

    <%= @tasks.each do |task| %>
      <%= task.name %><br>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(".nav-tabs li").removeClass("active");
  $(".nav-tabs li")[2].className += "active";
</script>

app/views/landing/index.html.erb
<h1 class="landing-title">Start to Track your Time!!</h1>

<pre>there is only a way to improve yourself it's called discipline.</pre>
<pre>you will get better results in every area of your life just being organized with your time.</pre>
<pre style="margin-bottom: 50px">that's the unique proposite of this app, let's be a monkey genius.</pre>

<% unless user_signed_in? %>
  <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-large btn-info lnd-btn" %>
  <%= link_to 'Sign In', new_user_session_path, class: "btn btn-large btn-info lnd-btn" %>
<% end %>

app/views/layouts/_header.html.erb
<div class="hero-unit" style="padding-top: 30px;">
  <h1> !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! !ˆˆ! </h1>
  <div class="muted">
    "El que vive sin disciplina muere sin honor" -
    <a href="https://www.github.com/tille" class="muted">T!ll3</a>

    <% if user_signed_in? %>
      <div class="navbar">
        <%= current_user.email %> |
        <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "muted" %>
      </div>
    <% end %>

  </div>
</div>

<% if user_signed_in? %>
  <ul class="nav nav-tabs">
    <li><a href="#">Check week progress</a></li>
    <li class="active"><a href="/dashboard">Items section</a></li>
    <li><a href="/free_tracker/tasks">free tracking section</a></li>
    <li><a href="#">pending priority tasks</a></li>
  </ul><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>T!ll3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/header" %>

  <div id="contents">
    <%= yield %>
  </div>

</body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>